

export const CATEGORIES_SEARCHED = 'CATEGORIES_SEARCHED'
export const GET_CATEGORIES = 'GET_CATEGORIES'


export const COMMENTS_SEARCHED = 'COMMENTS_SEARCHED'
export const COMMENT_VOTED = 'COMMENT_VOTED'
export const COMMENT_CREATED = 'COMMENT_CREATED'
export const COMMENT_UPDATED = 'COMMENT_UPDATED'
export const COMMENT_DELETED = 'COMMENT_DELETED'
export const OPEN_MODAL_COMMENT = 'OPEN_MODAL_COMMENT'
export const CLOSE_MODAL_COMMENT = 'CLOSE_MODAL_COMMENT'


export const POSTS_SEARCHED = 'POST_SEARCHED'
export const POST_LOADED  = 'POST_LOADED'
export const POST_FAILED  = 'POST_FAILED'
export const POST_CREATED = 'POST_CREATED'
export const POST_UPDATED = 'POST_UPDATED'
export const POST_DELETED = 'POST_DELETED'
export const POST_VOTED = 'POST_VOTED'
export const UPDATE_SORT_ATTRIBUTE = 'UPDATE_SORT_ATTRIBUTE'



